### ISSUE TITLE
Incorrect type definition for CompletionCreateParams.ToolChoice

### ISSUE THREAD

**Issue by domleboss97** [groq/groq-typescript#38] opened 2024-05-15 20:30 UTC
The [definition](https://github.com/groq/groq-typescript/blob/5de77530e22c10a06b5e042a4bed4e832e9dc9e5/src/resources/chat/completions.ts#L216) of `CompletionCreateParams.ToolChoice` is the following interface:

```
export interface ToolChoice {
  string?: string;

  toolChoice?: ToolChoice.ToolChoice;
}
```

I inferred from this type, that to specify `tool_choice: "none"`, one would have to do the following.
```
    const completion = await groq.chat.completions.create({
      model,
      messages,
      tools,
      tool_choice: { string: "none" },
})
```

However this leads to the following 400 error:
```
Error: 400 {"error":{"message":"Requested tool '' does not exist.","type":"invalid_request_error"}}
```

When I instead specify the tool_choice directly (i.e. `tool_choice: "none"`), the request is successful and no tools are invoked, as expected. However, this causes a TS error that I need to ignore.

It appears to me that the type definition of tool choice is incorrect. The toolchoice field of the `CompletionCreateParams` should be of type `string | ToolChoice`.

**Comment by gradenr** [comment] 2024-05-23 03:41
Thanks for pointing this out.  This should be fixed in the latest release (v0.4.0).

**Comment by gradenr** [comment] 2024-05-23 05:06
Please let me know if the issue is fixed

**Comment by domleboss97** [comment] 2024-05-23 12:41
Yes, thank you very much! One question - the `tools_choice` type still excludes the `required` value that the openai api supports. Have you all not implemented that on your end? Just confirming.

**Comment by gradenr** [comment] 2024-05-28 22:47
Groq API does not currently support `required`. I believe this is being worked on.

**Comment by gradenr** [comment] 2024-07-02 15:20
We have added support for `required`

**Closed by gradenr** 2024-07-02 15:20 UTC
